### ISSUE TITLE
Implement zone entry notices

### ISSUE THREAD

**Issue by stevewgr** [ko4life-net/ko#139]
#### Description

Implement zone entry notices, when walking into specific area, for example Arena, it shows yellow text in front top which area we entered.

#### Tasks

- [ ] This requires loading *.evtsub files
- [ ] Implementing CDFontFade that allows to render text that fades out
- [ ] Also CEventSubManager is required to be implemented
