### ISSUE TITLE
Implement Seeking party board ( Party bbs) UIF 

### ISSUE THREAD

**Issue by xGuTeK** [ko4life-net/ko#215]
#### Description
Implement Seeking party board ( Party bbs) UIF 

This is where we see all people that searching party 

#### Tasks
- [ ] Show seeking party board after press search party or something like that on command list
- [ ] fix uif 1264 display correctly 
- [ ] register, unregister on board should work but we need to check other buttons and make it work

**Comment by xGuTeK** [comment]
@stevewgr I need reverse engineering code ;)

**Comment by UTengine** [comment]
Why not share the whole database on functions and what is reversed already?

**Comment by stevewgr** [comment]
> Why not share the whole database on functions and what is reversed already?

When I do revers engineering, I just reverse the bits I need for certain implementations. I use like 5-10 idbs from multiple versions, so I don't have a proper one to share that will be of any use honestly. I rarely even put much efforts in renaming functions.
You could also download IDA and try it out, let me know where I can help in finding stuff and I'll also help in reversing certain implementations. I haven't looked at all how the party board implementation works, but feel free to even send a draft incomplete PR and we can go through it together.

**Comment by UTengine** [comment]
I see, well there is a party bbs working already so most functions should be there like register etc etc. It's just changed graphically if you want to see how it works I would suggest using the 1097 uif for seeking party and co_inn since it has 4 buttons.
Inn hostess
Create clan
Seeking party
Exit 

If im not mistaking

**Comment by UTengine** [comment]
That's a good offer Steve I've tried renaming based on pseudo code but It's too difficult with all the random v1=v3 v3= etcetera. I could seriously use some help
