### ISSUE TITLE
Produce sources from implode, jpeg and JvCryption libraries

### ISSUE THREAD

**Issue by stevewgr** [ko4life-net/ko#38]
#### Description

Part of the migration to modern compilers: https://github.com/stevewgr/ko/pull/30
The implode, jpeg and JvCryption libraries are used by multiple projects and compiled with old configurations.
Due to this, it forces the project configurations to be build with `ImageHasSafeExceptionHandlers` set to `false`, as well as ignore `libc.lib` to prevent linking errors.

Therefore it will be ideal to get ride of depends so that everything is built with the same build configurations to have a clean build.

### Tasks

- [x] Build jpeg.lib from source
  - [x] https://github.com/stevewgr/ko-vendor/pull/5
  - [x] https://github.com/stevewgr/ko/pull/50
- [x] Build implode from source
- [x] Build JvCryption from source
- [x] Get ride of `ImageHasSafeExceptionHandlers` in Release builds
- [x] Remove ignore `libc.lib` in project configs

**Comment by stevewgr** [comment]
For the record in terms of implode pkware compression library: https://github.com/ladislav-zezula/StormLib/tree/master/src/pklib

**Comment by stevewgr** [comment]
jpeg alternative: https://github.com/mozilla/mozjpeg

**Comment by UTengine** [comment]
Trust me don't remove jvcryption just yet it produces I'll effects with npcs not showing up near you. Other ppl removed it and just added the cryption key. And use lz4 compress and it fails to display npc near you unless you walk all the way to the moradon gate and back again

**Comment by UTengine** [comment]
Oopsie

**Comment by stevewgr** [comment]
- [x] Jpeg library was updated.

**Comment by stevewgr** [comment]
For the record, these are the current leftovers:
```
$ find engine game tool server -iname "*.lib"
game/Implode.lib
game/JvCryption.lib
server/AIServer/IMPLODE.LIB
server/AIServer/LibsIncs/IMPLODE.LIB
server/AIServer/LibsIncs/ServerComp.lib
server/AIServer/LibsIncs/ServerCompd.lib
server/Ebenezer/Implode.lib
server/Ebenezer/JvCryption.lib
```
I think getting ride of implode.lib first would be ideal.

**Comment by stevewgr** [comment]
Note that it looks like Ebenezer IMPLODE.H was changed in comparison to the regular buffer size of implode library:
![image](https://user-images.githubusercontent.com/90905675/181923677-4ffe467d-e9b7-4e25-aa48-c59736829f0a.png)

Other than that, all of the implode libs produce the same checksum:
![image](https://user-images.githubusercontent.com/90905675/181923789-d6f47b70-432e-4eae-bc75-d468e531cb4c.png)

This said, they're same builds just copied under multiple projects. This also means it would be also safe centeralizing them to use the same lib.

**Comment by stevewgr** [comment]
Git ride of JvCryption here: https://github.com/ko4life-net/ko/pull/146

Next step is getting ride of implode to finalize this.

**Comment by stevewgr** [comment]
> Trust me don't remove jvcryption just yet it produces I'll effects with npcs not showing up near you. Other ppl removed it and just added the cryption key. And use lz4 compress and it fails to display npc near you unless you walk all the way to the moradon gate and back again

@UTengine, I have no idea what you talking about. None of these issues happened for me while doing this: https://github.com/ko4life-net/ko/pull/150

You or they must have messed up something else for this to happen.
