### ISSUE TITLE
Upgrade UIs to 1264 so that the client will be in English

### ISSUE THREAD

**Issue by stevewgr** [ko4life-net/ko#88]
#### Description

Currently the UIs are in Korean.

We need to make the old school 1097 client UIs support English.

Note that the 1264 client UIs is the first client to be in English.

#### Tasks

- [x] Update ko-assets and remove all UIs and then replace them with the UIs from 1264 client
- [x] Make the client sources loading the UIs.tbl from 1264 client
- [x] Update the sources to load the new UIs

**Comment by JanekCode** [comment]
@stevewgr so what we will do taking some from 1298 UI's? Or just one by one translate?

**Comment by stevewgr** [comment]
> @stevewgr so what we will do taking some from 1298 UI's? Or just one by one translate?

Thanks @JanekCode. It was before we figured the 1264 UIs has them in English and similar to the old 1097 version. We went with updating the sources to match the 1264 UIs. I updated the ticket description.

**Comment by stevewgr** [comment]
Closing this issue considering the current state of master branch have this working.
