### ISSUE TITLE
Convert all varchar db columns used as binary to binary format

### ISSUE THREAD

**Issue by stevewgr** [ko4life-net/ko#94]
#### Description

Note that there are some columns in database being read as binary, but specify column data type as varchar.

This causes other issues, as it breaks scripting when special characters are produced from the binary format, varchar is being treated as string.

#### Tasks
- [x] Convert USERDATA strSkill and strItem to binary
- [x] Update all dependents stored procedures to use binary format
- [x] Verify that server code reads it right
- [x] Produce a migration script and a PR for ko-db repo

**Comment by stevewgr** [comment]
@xGuTeK, let me know if interesting working on this, otherwise I'll un-assign you so that it's easier to know who is working on what.

**Comment by srmeier** [comment]
The `[UPDATE_WAREHOUSE]` procedure and `WAREHOUSE` table also need adjusting.

**Comment by stevewgr** [comment]
Nice work @srmeier! Thanks for the help with that. We can now close this ticket as solved. 🎉
